<?php
/**
 * Created by PhpStorm.
 * User: susunsheng
 * Date: 16/6/11
 * Time: 下午11:41
 */

namespace Portal\Controller;

//use Think\Controller;
use Common\Controller\HomebaseController;

define(CONTROLLER, __CONTROLLER__);

class  JoinController extends HomebaseController{




    function index(){
        //获取系统常量, 并分组
        //var_dump(get_defined_constants(true));
        \Think\Log::write('index','info');

        $user = session('user');

        if($user){
            //用户 可以直接登录界面
            \Think\Log::write('index: '.$user.mobile,'info');

            $this->check_login();
            $return_url = U("portal/doctor/index",'',true,true);
            redirect($return_url, 1, '正在登录, 请稍等...');
        }
        else{
            $this->display();
        }
    }

    /**
     * @param $return_url
     */
    public function check_wechat_user()
    {
        \Think\Log::write('check_wechat_user:','info');
        $user = session('user');
        if(!$user){
            $user = $this->get_wechat_user();
            session('user', $user);
        }

        \Think\Log::write('check_wechat_user $user:'.$user,'info');

        if ($user) {
            if($user['user_type'] == DOCTOR){
                $doctorId = $this->get_doctor_id();
                session('doctor', $doctorId);
                \Think\Log::write('check_wechat_user $doctorId: '.$doctorId,'info');

                $return_url = U("portal/doctor/index",'',true,true);
            }

            redirect($return_url, 2, 'please wait...');
        }
    }


    function checkUser(){
        $phoneNumber = $_POST['to'];

        $where['mobile']=$phoneNumber;

        $users_model=M("Users");
        $result = $users_model->where($where)->count();
        \Think\Log::write('register $result:'.$result, "INFO");

        if($result){
            $ret['rescode'] = "01";
            $ret['msg'] = "验证通过, 成功登录";
            $this->user_login($phoneNumber);
//            $ret['msg'] = "手机号已被注册";
            //直接通过
            //还需要处理
            //不会发生这种情况
            //增加第一次登入积分
            \Think\Log::write('login success: ', "INFO");
            $doctorController = new DoctorController();
            $doctorId = $doctorController->get_doctor_id();
            \Think\Log::write('login success: doctorId: ' . $doctorId, "INFO");
            $doctorController->addLoginScore();

        }
        else{
            $ret['rescode'] = "00";
            $ret['msg'] = "验证通过, 完善信息";
        }

        $this->ajaxReturn($ret);

    }

    function user_logout()
    {
        parent::user_logout(); // TODO: Change the autogenerated stub
    }

}